### ISSUE TITLE
编译源码遇到个启动FC问题，Galaxy S6，M系统。

### ISSUE THREAD

**Issue by klpchan** [Trinea/android-demo#11]
07-26 19:12:18.151: E/AndroidRuntime(9545): FATAL EXCEPTION: main
07-26 19:12:18.151: E/AndroidRuntime(9545): Process: cn.trinea.android.demo, PID: 9545
07-26 19:12:18.151: E/AndroidRuntime(9545): java.lang.NoClassDefFoundError: Failed resolution of: Lcn/trinea/android/demo/ViewPagerDemo;
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at cn.trinea.android.demo.utils.AppUtils.getText(AppUtils.java:106)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at cn.trinea.android.demo.utils.AppUtils.initTrineaInfo(AppUtils.java:70)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at cn.trinea.android.demo.utils.AppUtils.init(AppUtils.java:38)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at cn.trinea.android.demo.BaseActivity.onCreate(BaseActivity.java:26)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at cn.trinea.android.demo.MainActivity.onCreate(MainActivity.java:32)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.app.Activity.performCreate(Activity.java:6904)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.os.Looper.loop(Looper.java:148)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at java.lang.reflect.Method.invoke(Native Method)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-26 19:12:18.151: E/AndroidRuntime(9545): Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.trinea.android.demo.ViewPagerDemo" on path: DexPathList[[zip file "/data/app/cn.trinea.android.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/cn.trinea.android.demo-2/lib/arm64, /vendor/lib64, /system/lib64]]
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-26 19:12:18.151: E/AndroidRuntime(9545): 	... 17 more
07-26 19:12:18.151: E/AndroidRuntime(9545): 	Suppressed: java.lang.NoClassDefFoundError: cn.trinea.android.demo.ViewPagerDemo
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at dalvik.system.DexFile.defineClassNative(Native Method)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		... 19 more
07-26 19:12:18.151: E/AndroidRuntime(9545): 	Suppressed: java.lang.ClassNotFoundException: cn.trinea.android.demo.ViewPagerDemo
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at java.lang.Class.classForName(Native Method)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-26 19:12:18.151: E/AndroidRuntime(9545): 		... 18 more
07-26 19:12:18.151: E/AndroidRuntime(9545): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by klpchan** [comment]
从网站上直接下的示例代码安装是没问题的。

**Comment by klpchan** [comment]
从网站直接下载的示例apk安装时没有问题的。
